name: Linting

on:
  pull_request:

jobs:
  clippy_format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Obtain Rust
      run: rustup override set ${{ matrix.rust }}
    - name: Check clippy
      run: rustup component add clippy && cargo clippy
    - name: Check formatting
      run: rustup component add rustfmt && cargo fmt -- --check
